# 历史记录限制
set -g history-limit 10000

# 设置默认终端为256色
set -g default-terminal "tmux-256color"

# 启用鼠标支持
set -g mouse on

# 启用vi模式键
setw -g mode-keys vi

# 复制模式中vi风格的绑定
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# 设置prefix键为Ctrl-a（替代默认的Ctrl-b）
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# 窗口和面板从1开始计数（而不是0）
set -g base-index 1
setw -g pane-base-index 1

# 重新加载配置文件快捷键
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# 使用 fzf 切换会话
bind s popup -EE "tmux list-sessions -F '#S' | fzf | xargs -r tmux switch-client -t"

# 分割窗口快捷键
bind | split-window -h  # 垂直分割
bind - split-window -v  # 水平分割
unbind '"'              # 取消默认分割快捷键
unbind %               

# 面板切换使用Alt+方向键
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# 窗口切换使用 prefix + n/p
bind p previous-window
bind n next-window

# 整体状态栏背景（深蓝）
set -g status-style "bg=#24273A,fg=#CAD3F5"
# 不活跃窗口（柔和蓝）
set -g window-status-style "bg=#24273A,fg=#8AADF4"
# 当前窗口（亮蓝高亮）
set -g window-status-current-style "bg=#B7BDF8,fg=#1E2030,bold"
# # 窗口样式
# # 非当前窗口：淡蓝（Sapphire）
setw -g window-status-style fg=#8AADF4,bg=#24273A
# 格式
setw -g window-status-format " #I:#W "
setw -g window-status-current-format "#[fg=#1E2030,bg=#8BC3FA,bold] #I:#W "
# 消息栏颜色
set -g message-style "bg=#1E2030,fg=#8BC3FA"
setw -g mode-style "fg=#4c4f69,bg=#8caaee"
# 左右侧
set -g status-left "#[fg=#8BC3FA,bold]#S "
set -g status-right "#[fg=colour153]%Y-%m-%d #[fg=#8AADF4]%H:%M "
