modmap:
  - name: CapsLock -> Esc/Ctrl_L
    remap:
      CapsLock:
        alone: Esc
        held: Ctrl_L
        alone_timeout_millis: 200
      Esc: CapsLock
  - name: Space -> Space/Shift_L
    remap:
      Space:
        held: Shift_L
        alone: Space
        hold_threshold_millis: 300
        free_hold: true
keymap:
  - name: obsidian (modified from Default)
    application:
      only: obsidian
    remap:
      # C-b: left  # for Vim
      # C-f: right # for Vim
      C-k: up
      C-j: down
